import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { Badge, Card, PageShell, Section, SIGNAL_TONE } from "@/components/ui";
import { ROUND_LABEL, type RoundType } from "@/lib/interview/rounds";
import { COMPANY_PROFILES } from "@/lib/interview/companies";
import type { FeedbackReport } from "@/lib/feedback/schema";

export const metadata = { title: "Feedback" };

/**
 * Every debrief the candidate has, in one place -- the thing they came back
 * to check without digging through History first. This is the product's core
 * differentiator, so it gets its own top-level page rather than being a tab
 * buried under something else.
 *
 * Two kinds of debrief exist and both belong here: a full-loop verdict
 * (multiple rounds combined) and a single round's feedback. Both are read
 * straight from data that already exists -- nothing new is generated by
 * visiting this page.
 */
export default async function FeedbackPage() {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) redirect("/login");

  const admin = createAdminClient();

  const { data: loops } = await admin
    .from("loops")
    .select("id, company, level, rounds, overall_signal, summary, completed_at")
    .eq("user_id", user.id)
    .not("overall_signal", "is", null)
    .order("completed_at", { ascending: false });

  const { data: sessions } = await admin
    .from("sessions")
    .select(
      "id, started_at, round_type, loop_id, loops(company, level), feedback(overall_signal, content)"
    )
    .eq("user_id", user.id)
    .order("started_at", { ascending: false });

  const withFeedback = (sessions ?? []).filter((s) => {
    const fb = Array.isArray(s.feedback) ? s.feedback[0] : s.feedback;
    return Boolean(fb);
  });

  const hasAnything = (loops?.length ?? 0) > 0 || withFeedback.length > 0;

  return (
    <PageShell
      width="lg"
      title="Feedback"
      description="Every debrief you've earned, in one place. This is what a real interviewer would write after your loop."
    >
      {!hasAnything && (
        <Card className="py-12 text-center">
          <p className="text-sm font-medium text-primary">No debriefs yet</p>
          <p className="mx-auto mt-1.5 max-w-sm text-sm leading-relaxed text-secondary">
            Finish a practice interview and its feedback will show up here.
          </p>
        </Card>
      )}

      {loops && loops.length > 0 && (
        <Section title="Full loop verdicts">
          <div className="space-y-2">
            {loops.map((l) => {
              const profile = COMPANY_PROFILES[l.company];
              const level = profile?.levels[l.level]?.label ?? l.level;
              const summary = l.summary as { headline?: string } | null;
              return (
                <Card
                  key={l.id}
                  href={`/loop/${l.id}`}
                  className="flex flex-wrap items-center justify-between gap-3 px-5 py-4"
                >
                  <div className="min-w-0">
                    <p className="truncate text-sm font-medium text-primary">
                      {profile?.displayName ?? l.company} · {level}
                    </p>
                    <p className="mt-1 truncate text-xs text-secondary">
                      {summary?.headline ?? `${l.rounds.length} rounds`}
                    </p>
                  </div>
                  <Badge tone={SIGNAL_TONE[l.overall_signal!] ?? "neutral"}>
                    {l.overall_signal}
                  </Badge>
                </Card>
              );
            })}
          </div>
        </Section>
      )}

      <Section
        title="Round feedback"
        actions={
          withFeedback.length > 0 && (
            <span className="text-xs text-muted">{withFeedback.length} shown</span>
          )
        }
      >
        {withFeedback.length === 0 ? (
          loops && loops.length > 0 ? null : (
            <Card className="py-8 text-center">
              <p className="text-sm text-secondary">Nothing here yet.</p>
            </Card>
          )
        ) : (
          <div className="space-y-2">
            {withFeedback.map((s) => {
              const fb = Array.isArray(s.feedback) ? s.feedback[0] : s.feedback;
              const signal = fb?.overall_signal as string | undefined;
              const content = fb?.content as FeedbackReport | null;
              const loop = Array.isArray(s.loops) ? s.loops[0] : s.loops;
              const company = loop ? COMPANY_PROFILES[loop.company] : null;
              const level = company?.levels[loop!.level]?.label ?? loop?.level;

              return (
                <Card
                  key={s.id}
                  href={`/session/${s.id}/feedback`}
                  className="px-5 py-4"
                >
                  <div className="flex flex-wrap items-center justify-between gap-3">
                    <div className="min-w-0">
                      <p className="truncate text-sm font-medium text-primary">
                        {company ? `${company.displayName} · ${level}` : "Practice interview"}
                      </p>
                      <p className="mt-1 flex flex-wrap items-center gap-2 text-xs text-muted">
                        <span>{ROUND_LABEL[s.round_type as RoundType] ?? s.round_type}</span>
                        <span aria-hidden>·</span>
                        <time dateTime={s.started_at}>
                          {new Date(s.started_at).toLocaleDateString(undefined, { dateStyle: "medium" })}
                        </time>
                      </p>
                    </div>
                    {signal && <Badge tone={SIGNAL_TONE[signal] ?? "neutral"}>{signal}</Badge>}
                  </div>
                  {content?.overallSummary && (
                    <p className="mt-3 line-clamp-2 text-sm leading-relaxed text-secondary">
                      {content.overallSummary}
                    </p>
                  )}
                </Card>
              );
            })}
          </div>
        )}
      </Section>
    </PageShell>
  );
}
