/**
 * Sends personalized cold-outreach emails to CS school contacts (club
 * officers, career centers) via Resend, from aryan@loopready.io.
 *
 * Reads a CSV with columns: school,contact_type,contact_name,email
 * contact_type is "club" or "career-center" — each gets different copy.
 *
 * Sends in small batches with a delay between each, not all at once: a
 * brand-new sending domain has no reputation yet, and pacing outreach like a
 * human rather than a blast is both safer for deliverability and honestly
 * how it should be sent anyway.
 *
 *   npx tsx scripts/send-campus-outreach.mts contacts.csv            # dry run, prints what would send
 *   npx tsx scripts/send-campus-outreach.mts contacts.csv --send     # actually sends
 *   npx tsx scripts/send-campus-outreach.mts contacts.csv --send --limit 20   # cap this run
 */
import { readFileSync, appendFileSync, existsSync } from "node:fs";
import { Resend } from "resend";

for (const line of readFileSync(".env.local", "utf8").split("\n")) {
  const m = /^([A-Z0-9_]+)=(.*)$/.exec(line.trim());
  if (m) process.env[m[1]] ??= m[2].replace(/^["']|["']$/g, "");
}

const RESEND_API_KEY = process.env.RESEND_API_KEY;
if (!RESEND_API_KEY) throw new Error("RESEND_API_KEY missing from .env.local");
const resend = new Resend(RESEND_API_KEY);

const FROM = "Aryan from LoopReady <aryan@loopready.io>";
// Per-school code, e.g. STANFORD10 -- generated by
// scripts/generate-college-codes.mts, one per school, $10 off. Falls back to
// the old flat CAMPUS20 code only for a school not in that mapping yet, so
// adding a new contact ahead of running the generator does not crash a send.
const FALLBACK_DISCOUNT_CODE = "CAMPUS20";
const CODE_BY_SCHOOL = parseSchoolCodes();
const DELAY_MS = 4000; // pace sends, don't blast

function parseSchoolCodes(): Map<string, string> {
  const map = new Map<string, string>();
  if (!existsSync("scripts/college-discount-codes.csv")) return map;
  const [, ...rows] = readFileSync("scripts/college-discount-codes.csv", "utf8").trim().split("\n");
  for (const row of rows) {
    const m = /^"(.+)",(\S+)$/.exec(row.trim());
    if (m) map.set(m[1], m[2]);
  }
  return map;
}

const csvPath = process.argv[2];
if (!csvPath) {
  console.log("Usage: npx tsx scripts/send-campus-outreach.mts contacts.csv [--send] [--limit N]");
  process.exit(1);
}
const SEND = process.argv.includes("--send");
const limitFlag = process.argv.indexOf("--limit");
const LIMIT = limitFlag !== -1 ? Number(process.argv[limitFlag + 1]) : Infinity;

interface Contact {
  school: string;
  contact_type: "club" | "career-center" | string;
  contact_name: string;
  email: string;
}

function parseCsv(raw: string): Contact[] {
  const [header, ...rows] = raw.trim().split("\n");
  const cols = header.split(",").map((c) => c.trim());
  return rows
    .filter((r) => r.trim())
    .map((row) => {
      // Naive split is fine here: contact names/schools in this list don't contain commas.
      const values = row.split(",").map((v) => v.trim());
      const rec = Object.fromEntries(cols.map((c, i) => [c, values[i] ?? ""]));
      return rec as unknown as Contact;
    });
}

function subjectFor(c: Contact): string {
  return c.contact_type === "club"
    ? `Free live mock-interview demo for your club?`
    : `A free interview-prep resource for ${c.school} students`;
}

function bodyFor(c: Contact): string {
  const greeting = c.contact_name && c.contact_name !== "—" ? `Hi ${c.contact_name},` : "Hi,";
  const checkoutUrl = "https://loopready.io/checkout?plan=voice";
  const code = CODE_BY_SCHOOL.get(c.school) ?? FALLBACK_DISCOUNT_CODE;

  if (c.contact_type === "club") {
    return `${greeting}

I'm Aryan, the founder of LoopReady — an AI that runs full FAANG interview loops (behavioral, coding, system design) out loud, and gives honest feedback on whether you'd have passed at a specific company and level.

I'd love to do a free 15-20 minute live demo for your club — running a mock interview on stage in front of the group, then opening it up for anyone to try. It's genuinely useful prep content for members, not a sales pitch.

Also happy to just share a discount code with your members either way: ${code} gets $10 off the first month (Voice: $9, Premium: $59) at ${checkoutUrl}.

Would a live demo be something your club's interested in this semester? Happy to work around your meeting schedule.

Thanks,
Aryan
Founder, LoopReady
https://loopready.io`;
  }

  return `${greeting}

I'm Aryan, the founder of LoopReady — an AI that runs full FAANG interview loops (behavioral, coding, system design) out loud, and gives honest feedback on whether a candidate would have passed at a specific company and level.

I wanted to share it as a free resource for ${c.school} students prepping for technical interviews — there's a free tier (one mock interview per week, no card required), and a discount code for students who want more: ${code} for $10 off the first month at ${checkoutUrl}.

If it'd be useful to share with students through your newsletter, job-search workshops, or resource list, I'm glad to send over more details or do a short demo.

Thanks for the work you do for students,
Aryan
Founder, LoopReady
https://loopready.io`;
}

async function main() {
  const contacts = parseCsv(readFileSync(csvPath, "utf8")).slice(0, LIMIT);
  console.log(`${contacts.length} contact(s) loaded from ${csvPath}. Mode: ${SEND ? "SENDING" : "DRY RUN"}\n`);

  const logPath = "scripts/campus-outreach-log.csv";
  if (SEND && !existsSync(logPath)) {
    appendFileSync(logPath, "timestamp,school,email,status\n");
  }

  for (const c of contacts) {
    if (!c.email || !c.email.includes("@")) {
      console.log(`SKIP (no valid email): ${c.school}`);
      continue;
    }
    const subject = subjectFor(c);
    const body = bodyFor(c);

    if (!SEND) {
      console.log(`--- DRY RUN: ${c.school} <${c.email}> ---`);
      console.log(`Subject: ${subject}`);
      console.log(body);
      console.log();
      continue;
    }

    try {
      await resend.emails.send({
        from: FROM,
        to: c.email,
        subject,
        text: body,
      });
      console.log(`SENT: ${c.school} <${c.email}>`);
      appendFileSync(logPath, `${new Date().toISOString()},"${c.school}",${c.email},sent\n`);
    } catch (e) {
      console.log(`FAILED: ${c.school} <${c.email}> — ${e instanceof Error ? e.message : e}`);
      appendFileSync(logPath, `${new Date().toISOString()},"${c.school}",${c.email},failed\n`);
    }

    await new Promise((r) => setTimeout(r, DELAY_MS));
  }
}

await main();
