/**
 * Sends personalized cold-outreach emails to CS school contacts (club
 * officers, career centers) via Resend, from aryan@loopready.io.
 *
 * Reads a CSV with columns: school,contact_type,contact_name,email
 * contact_type is "club" or "career-center" — each gets different copy.
 *
 * Sends in small batches with a delay between each, not all at once: a
 * brand-new sending domain has no reputation yet, and pacing outreach like a
 * human rather than a blast is both safer for deliverability and honestly
 * how it should be sent anyway.
 *
 *   npx tsx scripts/send-campus-outreach.mts contacts.csv            # dry run, prints what would send
 *   npx tsx scripts/send-campus-outreach.mts contacts.csv --send     # actually sends
 *   npx tsx scripts/send-campus-outreach.mts contacts.csv --send --limit 20   # cap this run
 */
import { readFileSync, writeFileSync, appendFileSync, existsSync } from "node:fs";
import { Resend } from "resend";

for (const line of readFileSync(".env.local", "utf8").split("\n")) {
  const m = /^([A-Z0-9_]+)=(.*)$/.exec(line.trim());
  if (m) process.env[m[1]] ??= m[2].replace(/^["']|["']$/g, "");
}

const RESEND_API_KEY = process.env.RESEND_API_KEY;
if (!RESEND_API_KEY) throw new Error("RESEND_API_KEY missing from .env.local");
const resend = new Resend(RESEND_API_KEY);

const FROM = "Aryan from LoopReady <aryan@loopready.io>";
const DELAY_MS = 4000; // pace sends, don't blast

// Per-school code, e.g. STANFORD10 -- generated by
// scripts/generate-college-codes.mts, one per school, $10 off. Not used in
// the first-touch email body (see bodyFor's own comment on why), but logged
// alongside each send so the code is on hand for the follow-up reply once
// there's a real conversation.
const CODE_BY_SCHOOL = parseSchoolCodes();

function parseSchoolCodes(): Map<string, string> {
  const map = new Map<string, string>();
  if (!existsSync("scripts/college-discount-codes.csv")) return map;
  const [, ...rows] = readFileSync("scripts/college-discount-codes.csv", "utf8").trim().split("\n");
  for (const row of rows) {
    const m = /^"(.+)",(\S+)$/.exec(row.trim());
    if (m) map.set(m[1], m[2]);
  }
  return map;
}

const csvPath = process.argv[2];
if (!csvPath) {
  console.log("Usage: npx tsx scripts/send-campus-outreach.mts contacts.csv [--send] [--limit N]");
  process.exit(1);
}
const SEND = process.argv.includes("--send");
const limitFlag = process.argv.indexOf("--limit");
const LIMIT = limitFlag !== -1 ? Number(process.argv[limitFlag + 1]) : Infinity;

interface Contact {
  school: string;
  contact_type: "club" | "career-center" | string;
  contact_name: string;
  email: string;
}

function parseCsv(raw: string): Contact[] {
  const [header, ...rows] = raw.trim().split("\n");
  const cols = header.split(",").map((c) => c.trim());
  return rows
    .filter((r) => r.trim())
    .map((row) => {
      // Naive split is fine here: contact names/schools in this list don't contain commas.
      const values = row.split(",").map((v) => v.trim());
      const rec = Object.fromEntries(cols.map((c, i) => [c, values[i] ?? ""]));
      return rec as unknown as Contact;
    });
}

function subjectFor(c: Contact): string {
  return `Interview prep resource for ${c.school} students`;
}

/**
 * Single unified template (no club/career-center split) -- deliberately
 * does not mention the actual discount code or a link in the first touch.
 * Naming a code/link is what pushed the earlier draft into Gmail's
 * Promotions tab; this reads as a partnership ask, and the code is offered
 * only as something to send "if useful," in a reply once there's a real
 * conversation. CODE_BY_SCHOOL still exists so that reply has a real code
 * ready to send.
 */
function bodyFor(c: Contact): string {
  const name = c.contact_name && c.contact_name !== "—" ? c.contact_name : "there";

  return `Hi ${name},

I'm Aryan, the founder of LoopReady, an AI-powered interview practice platform built to help students prepare for technical interviews.

With recruiting and interview preparation ramping up around this time of year, I wanted to reach out and see if we could make LoopReady available to ${c.school} students at a discounted rate.

LoopReady lets students practice full interview rounds for software engineering roles, including coding, behavioral, and system design, with an AI interviewer that asks follow-up questions and provides detailed feedback afterward.

My goal is simply to give students another resource they can use while preparing, especially for students who may not have access to regular mock interviews or someone to practice with.

I'd be happy to provide ${c.school} students with a dedicated discount code and, if helpful, share a short overview or demo that you could pass along to students through your career resources, workshops, or newsletter.

We'd love to support the students at ${c.school} and explore whether there's a way we can partner with you to make interview preparation a little more accessible.

Please let me know if this would be useful, and I'd be happy to send over the details.

Best,
Aryan
Founder, LoopReady
loopready.io`;
}

/**
 * scripts/campus-outreach-master.csv is the single source of truth for
 * "which real schools have we actually contacted" -- one row per school,
 * updated in place (not appended) so it always reflects current status
 * rather than requiring a reader to replay a log. Matched by school name,
 * since that's the one column every batch file and the master share.
 */
const MASTER_PATH = "scripts/campus-outreach-master.csv";

function markSent(school: string, status: "sent" | "failed") {
  if (!existsSync(MASTER_PATH)) return;
  const [header, ...rows] = readFileSync(MASTER_PATH, "utf8").trim().split("\n");
  const cols = header.split(",");
  const schoolIdx = cols.indexOf("school");
  const statusIdx = cols.indexOf("status");
  const sentAtIdx = cols.indexOf("sent_at");
  if (schoolIdx === -1 || statusIdx === -1) return;

  const now = new Date().toISOString();
  const updated = rows.map((row) => {
    const values = row.split(",");
    if (values[schoolIdx] !== school) return row;
    values[statusIdx] = status;
    if (sentAtIdx !== -1) values[sentAtIdx] = now;
    return values.join(",");
  });
  writeFileSync(MASTER_PATH, [header, ...updated].join("\n") + "\n");
}

/**
 * Schools that have explicitly asked not to be contacted again.
 *
 * Read from the master file's status column rather than a hardcoded list, so
 * recording an opt-out in one place is enough to permanently protect it. This
 * is a hard guard, not a convenience: re-running an old batch CSV that still
 * lists an opted-out school must never re-email them, in dry run or otherwise.
 * Lafayette College is the first -- they replied asking for no follow-ups.
 */
function doNotContactSet(): Set<string> {
  const out = new Set<string>();
  if (!existsSync(MASTER_PATH)) return out;
  const [header, ...rows] = readFileSync(MASTER_PATH, "utf8").trim().split("\n");
  const cols = header.split(",");
  const schoolIdx = cols.indexOf("school");
  const statusIdx = cols.indexOf("status");
  if (schoolIdx === -1 || statusIdx === -1) return out;
  for (const row of rows) {
    const values = row.split(",");
    if (values[statusIdx]?.startsWith("replied-do-not-contact")) {
      out.add(values[schoolIdx]);
    }
  }
  return out;
}

async function main() {
  const contacts = parseCsv(readFileSync(csvPath, "utf8")).slice(0, LIMIT);
  const blocked = doNotContactSet();
  console.log(`${contacts.length} contact(s) loaded from ${csvPath}. Mode: ${SEND ? "SENDING" : "DRY RUN"}`);
  if (blocked.size) console.log(`${blocked.size} school(s) on the do-not-contact list will be skipped.`);
  console.log();

  const logPath = "scripts/campus-outreach-log.csv";
  if (SEND && !existsSync(logPath)) {
    appendFileSync(logPath, "timestamp,school,email,status\n");
  }

  for (const c of contacts) {
    if (blocked.has(c.school)) {
      console.log(`SKIP (asked not to be contacted): ${c.school}`);
      continue;
    }
    if (!c.email || !c.email.includes("@")) {
      console.log(`SKIP (no valid email): ${c.school}`);
      continue;
    }
    const subject = subjectFor(c);
    const body = bodyFor(c);

    const code = CODE_BY_SCHOOL.get(c.school);

    if (!SEND) {
      console.log(`--- DRY RUN: ${c.school} <${c.email}> (code for follow-up: ${code ?? "none mapped"}) ---`);
      console.log(`Subject: ${subject}`);
      console.log(body);
      console.log();
      continue;
    }

    try {
      // The Resend SDK does NOT throw on an API-level failure (bad address,
      // domain not verified, etc) -- it resolves normally with an `error`
      // field. A bare await here would log every rejected send as "SENT"
      // and mark the school as contacted in the master file when it never
      // actually went out. Confirmed by test: sending to a deliberately
      // invalid address resolved without throwing and had `error` set.
      const { error } = await resend.emails.send({
        from: FROM,
        to: c.email,
        subject,
        text: body,
      });
      if (error) throw new Error(error.message);
      console.log(`SENT: ${c.school} <${c.email}> (code for follow-up: ${code ?? "none mapped"})`);
      appendFileSync(logPath, `${new Date().toISOString()},"${c.school}",${c.email},sent\n`);
      markSent(c.school, "sent");
    } catch (e) {
      console.log(`FAILED: ${c.school} <${c.email}> — ${e instanceof Error ? e.message : e}`);
      appendFileSync(logPath, `${new Date().toISOString()},"${c.school}",${c.email},failed\n`);
      markSent(c.school, "failed");
    }

    await new Promise((r) => setTimeout(r, DELAY_MS));
  }
}

await main();
